version: '3.8'

services:
  app:
    container_name: home-library-service
    build: .
    image: khvorosttt/home-library-service
    env_file:
      - .env
    environment:
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - ${PORT}:${PORT}
    restart: always
    depends_on:
      - postgres
    networks:
      - home-library-network
  postgres:
    container_name: postgres
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - home-library-network
volumes:
  pgdata:
networks:
  home-library-network:
    driver: bridge